// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Informedica.Build.Template")>]
[<assembly: AssemblyProductAttribute("Informedica.Build.Template")>]
[<assembly: AssemblyVersionAttribute("1.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-01-19T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("1.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("1.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","0259b952bbaa43a072788b2b4ec7d565c097c944")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Informedica.Build.Template"
    let [<Literal>] AssemblyProduct = "Informedica.Build.Template"
    let [<Literal>] AssemblyVersion = "1.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-01-19T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "1.1.1"
    let [<Literal>] AssemblyInformationalVersion = "1.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "0259b952bbaa43a072788b2b4ec7d565c097c944"
